### ISSUE TITLE
Conflict with GM Notes

### ISSUE THREAD

**Issue by Natrium617** [rlach/wiki-import#2]
For some reason the wiki import tab at the top of journal sheets disappears whenever GM Notes is loaded.
https://github.com/syl3r86/gm-notes
They are both amazing tools that I would love to use together.

Thx a bunch for looking into it

**Comment by rlach** [comment]
I can confirm the issue, and the fault lies on wiki-import side. I'll fix it sometime next week.

**Comment by rlach** [comment]
This is now fixed in version 0.9.3. Happy GM noting while importing from wiki 👍
