### ISSUE TITLE
Wiki Source Method Failing

### ISSUE THREAD

**Issue by RinVindor** [rlach/wiki-import#3]
I'm having an issue with the Wiki Source route, most work via the Wiki article URL but when trying the source option on the ones that give a CORS issue, nothing happens in the journal.

I've got the error it produces on screenshot.

This is on Foundry Version 0.8.9 

![image](https://user-images.githubusercontent.com/12647469/147005733-c98a9402-f100-4e46-bd64-98276fc50b90.png)

**Comment by rlach** [comment]
I can replicate it with https://whitewolf.fandom.com/wiki/Spirit_(MTAs)

Not sure if I'll have time to fix it before xmass though.

**Comment by RinVindor** [comment]
No worries just wanted to get this out to you :) I love the module as it was something I had been hoping someone more capable than I am at programming would come up with. Now its just gonna take me ages to grab the pages I want. 

I do have some suggestions though for improvements but I'll make separate tickets for those. Have a good holiday!

**Comment by rlach** [comment]
This was an issue with interwiki links. Will be fixed in new version.
