### ISSUE TITLE
Debugging wtf.fetch

### ISSUE THREAD

**Issue by gmillerd** [rlach/wiki-import#4]
Hello,

Would you please consider:

- adding debugging to the logging your external requests?
- Perhaps also 'how to know if you are encountering a cors issue, eg ... how to confirm you got it right with curl. https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl
- a note about authentication

**Comment by rlach** [comment]
If you install modle `Developer mode` and enable `debug flags -> package specific flags -> wiki to journal importer` you'll be seeing the exception returned by wtf.fetch. In the next release I'll also add a log that will throw the results of successful fetch into the console. Those logs will be hidden unless the Developer mode flags are enabled. Anything more than that and I would have to make the logs inside the fetch itself and I don't want to do it, as it would make updating wtf wiki in the future.

For CORS I plan to add a feature to use cors proxy to avoid it, so I'll be doing some kind of interface for CORS settings with that, and will include some kind of message.

For now I hope simple notes like this will work:

<img width="416" alt="Zrzut ekranu 2022-01-6 o 21 37 52" src="https://user-images.githubusercontent.com/5655000/148448492-94f03eb1-450c-4b22-bf59-5acccd20bd9b.png">

With a link to this: https://github.com/rlach/wiki-import/wiki/About-CORS

**Comment by gmillerd** [comment]
Thanks!
