### ISSUE TITLE
[Bug Report] Version 10 Prototype 3 Module Broken

### ISSUE THREAD

**Issue by RinVindor** [rlach/wiki-import#7]
Just as a heads up the module is broken for the new version of Foundry now that journals are using ProseMirror. When importing through the Wiki button, nothing happens.

![image](https://user-images.githubusercontent.com/12647469/172689698-be637da4-2952-465e-9d39-7fcf70bb46f1.png)

**Comment by rlach** [comment]
Thanks for the heads up. I'll try to prepare it for v10 before it releases.

**Comment by RinVindor** [comment]
Hey just wanted to see if there was any updates on this since V10 is officially out now 😁

**Comment by RinVindor** [comment]
I was able to get this working with the help of #arcanist4317 helping me on the Foundry Discord. Within the module.js at line 168-169
`                const [{ id }] = app.document.pages;
				app.document.updateEmbeddedDocuments("JournalEntryPage", [{ _id: id, "text.content": content }]);`

**Comment by rlach** [comment]
I've decided to change the way the importer works a bit with this new update to v10. 

Now the importer will create a new page in currently opened journal. There will now be a field to input article name, but if yo leave it empty and use url method it will auto-name the new page.

This should be out today.

**Comment by RinVindor** [comment]
Thanks! 😅 I definitely was a bit worried I might have to take up the
mantle and make a fork

**Comment by rlach** [comment]
Fortunately it didn't have to come to that! ;) The update is now live
