### ISSUE TITLE
[Feature Request] Link Name Edit Upon Import

### ISSUE THREAD

**Issue by RinVindor** [rlach/wiki-import#8]
So been working on a Star Wars game coming up and using https://starwars.fandom.com aka Wookieepedia. As usual your module is invaluable! I've got this minor issue and dunno how common it is with other media but with Star Wars they have the Legends and "Canon" lots of us prefer to play in Legends canon. Well links for basically almost everything are separated with this https://starwars.fandom.com/wiki/Core_Worlds/Legends for a Legends page versus https://starwars.fandom.com/wiki/Core_Worlds for a Canon page.

Is there a way we could have it so that in the Settings for the module you can list characters to be removed UPON import? In this instance I'd have it set for "/Legends" to be removed upon importing, that way it imports the proper version I want but upon wrapping up said import every single reference in the text to /Legends for a link is removed?

I hope so cause doing it manually for every planet is brutal 😂thanks as always!

**Comment by rlach** [comment]
So we basically want to have all links like this:
`@JournalEntry[Coruscant/Legends]{Coruscant}`
be just this:
`@JournalEntry[Coruscant]{Coruscant}`

Sounds okay. I'll look into it.

**Comment by RinVindor** [comment]
Thanks I appreciate it!

**Comment by rlach** [comment]
You probably lost all hope. Yet there it is:

<img width="552" alt="Zrzut ekranu 2022-09-6 o 15 44 47" src="https://user-images.githubusercontent.com/5655000/188651097-fd8a30c6-9874-4b8e-be86-5fc14542ef75.png">

Should be out today. Although only for v10+ of Foundry.
